const {chromium}=require('playwright');
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert');
const base=path.resolve(__dirname,'..');const output=path.join(base,'test-artifacts');fs.mkdirSync(output,{recursive:true});
const server=http.createServer((req,res)=>{const file=path.join(base,decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!file.startsWith(base)){res.writeHead(403).end();return}fs.readFile(file,(err,body)=>{if(err){res.writeHead(404).end();return}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png'})[path.extname(file)]||'text/plain');res.end(body)})});
(async()=>{await new Promise(r=>server.listen(4173,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:"msedge"});const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});let errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/js/config.js',route=>route.fulfill({contentType:'text/javascript',body:'window.CLASH_CONFIG = {};'}));
await page.goto('http://127.0.0.1:4173');await page.waitForSelector('#pageLoader',{state:'detached'});assert.equal(await page.title(),'Arena');assert.equal(await page.locator('.welcome-image').evaluate(x=>x.naturalWidth),530);
for(const width of [320,390,430,768,1440]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow at '+width);}
await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'preview-mobile.png'),fullPage:true});
await page.getByRole('button',{name:'Detalhes +'}).click();assert.equal(await page.locator('#tableToggle').getAttribute('aria-expanded'),'true');await page.getByRole('button',{name:'Resumir'}).click();await page.getByRole('button',{name:'Agendadas',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Agendadas',exact:true}).getAttribute('aria-pressed'),'true');
await page.goto('http://127.0.0.1:4173/admin.html');await page.waitForSelector('#pageLoader',{state:'detached'});assert(await page.getByRole('heading',{name:'Conecte o Supabase'}).isVisible());assert.equal(errors.length,0,errors.join('\n'));console.log('PASS: widths 320/390/430/768/1440, image, filters, table, Admin setup, no page errors');

let saved={site_name:'Minha Arena',hero_title:'Torneio',hero_description:'',league_title:'Ranking',cup_title:'Copa',matches_title:'Jogos',footer_text:'',image_url:'assets/site-image.png',accent_color:'#ffca45',loading_text:'Aguarde',show_hero:true};
const fixtures={players:[{id:'p1',name:'Participante A'}],teams:[{id:'a',name:'Participante A',team_type:'SOLO'},{id:'b',name:'Participante B',team_type:'SOLO'},{id:'c',name:'Dupla A',team_type:'DUO'},{id:'d',name:'Dupla B',team_type:'DUO'}],team_members:[],competitions:[{id:'l',kind:'LEAGUE',mode:'SOLO',active:true,name:'Liga'},{id:'c',kind:'CUP',mode:'DUO',active:true,name:'Copa'}],matches:[{id:'1',competition_id:'l',participant_a:'a',participant_b:'b',crowns_a:3,crowns_b:0,status:'FINISHED',round_label:'Rodada 1',scheduled_at:'2026-09-20T12:00:00Z'},{id:'2',competition_id:'c',participant_a:'c',participant_b:'d',crowns_a:null,crowns_b:null,status:'SCHEDULED',round_label:'Final',scheduled_at:'2026-09-21T12:00:00Z'}],match_games:[{id:'g',match_id:'1',game_number:1,crowns_a:3,crowns_b:0}]};
await page.route('**/js/supabase-client.js',route=>route.fulfill({contentType:'text/javascript',body:
'export const configured=true;const fixtures='+JSON.stringify(fixtures)+';let settings='+JSON.stringify(saved)+';export const supabase={auth:{getSession:async()=>({data:{session:{user:{id:"admin"}}}}),signOut:async()=>({})},rpc:async()=>({data:true}),from(table){let payload;const query={select(){return this},order(){return this},eq(){return this},maybeSingle(){return this},upsert(value){payload=value;return this},then(resolve,reject){if(payload){settings=payload.settings;window.__saved=settings;return Promise.resolve({error:null}).then(resolve,reject)}return Promise.resolve({data:table==="site_settings"?{settings}:fixtures[table]||[],error:null}).then(resolve,reject)}};return query}};'}));
await page.goto('http://127.0.0.1:4173');await page.waitForSelector('#pageLoader',{state:'detached'});assert.equal(await page.title(),'Minha Arena');assert.deepEqual(await page.locator('.pts').allTextContents(),['3','-1']);assert.equal(await page.locator('.match-card').count(),2);
await page.getByRole('button',{name:'Agendadas',exact:true}).click();assert.equal(await page.locator('.match-card').count(),1);await page.getByRole('button',{name:'Finalizadas',exact:true}).click();await page.locator('summary').click();assert(await page.locator('.game-log').isVisible());
for(const width of [320,390,430,768,1440]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'populated overflow '+width)}
await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Todas',exact:true}).click();await page.evaluate(()=>{document.activeElement?.blur();window.scrollTo({top:0,behavior:'instant'})});await page.screenshot({path:path.join(output,'preview-populated.png'),fullPage:true});
await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.waitForFunction(()=>document.querySelector('.desktop-nav a.active')?.hash==='#campeonato');await page.screenshot({path:path.join(output,'preview-desktop.png'),fullPage:true});assert.equal(await page.locator('#teamCount').textContent(),'4');assert.equal(await page.locator('#scheduledCount').textContent(),'1');assert.equal(await page.locator('#finishedCount').textContent(),'1');await page.setViewportSize({width:390,height:844});
await page.goto('http://127.0.0.1:4173/admin.html');await page.getByRole('button',{name:'Aparência'}).click();await page.locator('[name=site_name]').fill('Nova Arena');await page.locator('[name=hero_title]').fill('');await page.locator('[name=primary_color]').fill('#245ca8');await page.locator('[name=participants_label]').fill('Equipes <b>');await page.locator('[name=empty_matches]').fill('Sem registros');await page.locator('[name=cta_label]').fill('Confrontos');await page.locator('[name=show_hero]').uncheck();await page.getByRole('button',{name:'Salvar alterações'}).click();await page.waitForFunction(()=>window.__saved?.site_name==='Nova Arena');saved=await page.evaluate(()=>window.__saved);assert.equal(saved.show_hero,false);assert.equal(saved.hero_title,'');assert.equal(saved.primary_color,'#245ca8');assert.equal(saved.cta_label,'Confrontos');assert.equal(saved.empty_matches,'Sem registros');assert(await page.locator('#settingsStatus').textContent().then(x=>x.includes('salvas')));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(output,'preview-admin.png'),fullPage:true});
await page.goto('http://127.0.0.1:4173');await page.waitForSelector('#pageLoader',{state:'detached'});assert.equal(await page.title(),'Nova Arena');assert(await page.locator('#inicio').isHidden());assert.equal(await page.locator('[data-setting=participants_label]').textContent(),'Equipes <b>');assert.equal(await page.locator('[data-setting=participants_label] b').count(),0);assert.equal(await page.evaluate(()=>document.documentElement.style.getPropertyValue('--royal')),'#245ca8');assert.equal(errors.length,0,errors.join('\n'));
assert.equal(await page.evaluate(async()=>{const {normalizeSettings}=await import('/js/settings.js');return normalizeSettings(null).site_name}),'Arena');
console.log('PASS: null settings, season counters, editable labels, escaped content, primary color save/reload');
console.log('PASS: mock backend: 3/-1 scoring, match filters, game detail, appearance save/reload, optional hero, mobile Admin');
await page.route('**/js/loading.js',async route=>{const response=await route.fetch();await route.fulfill({response,body:(await response.text()).replace('12000','1')})});
await page.goto('http://127.0.0.1:4173');await page.waitForFunction(()=>document.querySelector('#teamCount')?.textContent==='4');assert(await page.locator('#setupWarning').isHidden());await page.unroute('**/js/loading.js');console.log('PASS: successful data load clears timeout warning');
await page.unroute('**/js/supabase-client.js');await page.route('**/js/app.js',route=>route.abort());await page.goto('http://127.0.0.1:4173');await page.waitForSelector('#pageLoader',{state:'detached',timeout:15000});assert(await page.locator('#setupWarning').isVisible());console.log('PASS: failed module exits loading and shows retry message');
await browser.close();server.close();
})().catch(e=>{console.error(e);server.close();process.exitCode=1});


